<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMlbWjVC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMlbWjVC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMlbWjVC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMlbWjVC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMlbWjVC\App_KernelDevDebugContainer([
    'container.build_hash' => 'MlbWjVC',
    'container.build_id' => 'ea9ebf5f',
    'container.build_time' => 1694589816,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMlbWjVC');
